#!/bin/bash
set -u

GADGET_NAME="rukebox"
G="/sys/kernel/config/usb_gadget/$GADGET_NAME"

HOST_MAC="${RUKEBOX_USB_HOST_MAC:-02:1a:11:00:00:01}"
DEV_MAC="${RUKEBOX_USB_DEV_MAC:-02:1a:11:00:00:02}"

USB_INTERNET="${RUKEBOX_USB_INTERNET:-yes}"
NET_HOST_MAC="${RUKEBOX_USB_NET_HOST_MAC:-02:1a:11:00:01:01}"
NET_DEV_MAC="${RUKEBOX_USB_NET_DEV_MAC:-02:1a:11:00:01:02}"
NET_PI_ADDR="192.168.77.2/24"
NET_GATEWAY="192.168.77.1"

log() { echo "[usb-gadget] $*"; }

ENV_FILE="${RUKEBOX_ENV_FILE:-/etc/rukebox/rukebox.env}"
MODE="$(sed -n "s/^USB_PORT_MODE='\(.*\)'$/\1/p" "$ENV_FILE" 2>/dev/null | tail -1)"
[ "$MODE" = "host" ] || MODE="gadget"

CONFIG_TXT="/boot/firmware/config.txt"
[ -f "$CONFIG_TXT" ] || CONFIG_TXT="/boot/config.txt"
WANT_DR="otg"
[ "$MODE" = "host" ] && WANT_DR="host"
if [ -f "$CONFIG_TXT" ] && grep -q "^# rukebox: USB gadget mode" "$CONFIG_TXT"; then
    CURRENT_DR="$(sed -n '/^# rukebox: USB gadget mode/,/^dtoverlay=dwc2/ s/^dtoverlay=dwc2,dr_mode=\(.*\)$/\1/p' "$CONFIG_TXT" | head -1)"
    if [ -n "$CURRENT_DR" ] && [ "$CURRENT_DR" != "$WANT_DR" ]; then
        sed -i "/^# rukebox: USB gadget mode/,/^dtoverlay=dwc2/ s/^dtoverlay=dwc2,dr_mode=.*/dtoverlay=dwc2,dr_mode=$WANT_DR/" "$CONFIG_TXT"
        log "config.txt: dr_mode=$WANT_DR (takes effect after a reboot)"
    fi
fi

if [ "$MODE" = "host" ] && [ -z "$(ls /sys/class/udc 2>/dev/null)" ]; then
    log "USB_PORT_MODE=host: no gadget, the port is left to USB devices"
    exit 0
fi

if [ ! -d /sys/class/udc ]; then
    log "no /sys/class/udc, skipping"
    exit 0
fi
UDC="$(ls /sys/class/udc 2>/dev/null | head -1)"
if [ -z "$UDC" ]; then
    log "no USB device controller available, skipping"
    log "  (config.txt needs 'dtoverlay=dwc2,dr_mode=otg' under [all])"
    exit 0
fi

modprobe libcomposite 2>/dev/null || true
modprobe usb_f_ncm 2>/dev/null || true

if [ ! -d /sys/kernel/config/usb_gadget ]; then
    log "configfs gadget support unavailable, skipping"
    exit 0
fi

UDEV_RULE="/etc/udev/rules.d/99-rukebox-usb0.rules"
if [ -d /etc/udev/rules.d ] && ! grep -q 'usb\[01\]' "$UDEV_RULE" 2>/dev/null; then
    cat > "$UDEV_RULE" <<'UDEVEOF' 2>/dev/null || true
# Generated by rukebox (scripts/usb_gadget.sh) - see that file.
# Cancels /usr/lib/udev/rules.d/85-nm-unmanaged.rules for the two USB
# interfaces, so NetworkManager will actually manage the USB links.
SUBSYSTEM=="net", ACTION=="add|change|move", ENV{INTERFACE}=="usb[01]", ENV{NM_UNMANAGED}="0"
UDEVEOF
    udevadm control --reload-rules 2>/dev/null || true
    log "wrote $UDEV_RULE"
fi

NM_KEYFILE="/etc/NetworkManager/system-connections/usb0-static.nmconnection"
if [ -d /etc/NetworkManager/system-connections ] && [ ! -f "$NM_KEYFILE" ]; then
    cat > "$NM_KEYFILE" <<'NMEOF' 2>/dev/null || true
[connection]
id=usb0-static
type=ethernet
interface-name=usb0
autoconnect=true

[ipv4]
method=manual
address1=169.254.7.7/16

[ipv6]
method=ignore
NMEOF
    chmod 600 "$NM_KEYFILE" 2>/dev/null || true
    log "created $NM_KEYFILE"
fi

NM_NET_KEYFILE="/etc/NetworkManager/system-connections/usb1-internet.nmconnection"
if [ "$USB_INTERNET" = "yes" ] && [ -d /etc/NetworkManager/system-connections ] && [ ! -f "$NM_NET_KEYFILE" ]; then
    cat > "$NM_NET_KEYFILE" <<NMEOF 2>/dev/null || true
[connection]
id=usb1-internet
type=ethernet
interface-name=usb1
autoconnect=true

[ipv4]
method=manual
address1=$NET_PI_ADDR,$NET_GATEWAY
dns=1.1.1.1;9.9.9.9;
route-metric=700
may-fail=true

[ipv6]
method=ignore
NMEOF
    chmod 600 "$NM_NET_KEYFILE" 2>/dev/null || true
    log "created $NM_NET_KEYFILE"
fi

teardown() {
    [ -d "$G" ] || return 0
    echo "" > "$G/UDC" 2>/dev/null || true
    rm -f "$G/os_desc/c.1" 2>/dev/null || true
    rm -f "$G/configs/c.1/ncm.usb0" "$G/configs/c.1/ncm.usb1" 2>/dev/null || true
    rmdir "$G/configs/c.1/strings/0x409" 2>/dev/null || true
    rmdir "$G/configs/c.1" 2>/dev/null || true
    rmdir "$G/functions/ncm.usb0" "$G/functions/ncm.usb1" 2>/dev/null || true
    rmdir "$G/strings/0x409" 2>/dev/null || true
    rmdir "$G" 2>/dev/null || true
}
teardown

if [ "$MODE" = "host" ]; then
    log "USB_PORT_MODE=host: no gadget, the port is left to USB devices"
    exit 0
fi

mkdir -p "$G" || { log "could not create the gadget, skipping"; exit 0; }
cd "$G" || exit 0

echo 0x1d6b > idVendor
echo 0x0104 > idProduct
echo 0x0100 > bcdDevice
echo 0x0200 > bcdUSB

mkdir -p strings/0x409
echo "rukebox0001" > strings/0x409/serialnumber
echo "Rukebox"     > strings/0x409/manufacturer
echo "Rukebox USB" > strings/0x409/product

mkdir -p configs/c.1/strings/0x409
echo "NCM" > configs/c.1/strings/0x409/configuration
echo 250   > configs/c.1/MaxPower

# CDC-NCM, not g_ether: Windows 11 binds RNDIS as a serial port.
mkdir -p functions/ncm.usb0
echo "$HOST_MAC" > functions/ncm.usb0/host_addr
echo "$DEV_MAC"  > functions/ncm.usb0/dev_addr
if [ "$USB_INTERNET" = "yes" ]; then
    mkdir -p functions/ncm.usb1
    echo "$NET_HOST_MAC" > functions/ncm.usb1/host_addr
    echo "$NET_DEV_MAC"  > functions/ncm.usb1/dev_addr
fi

if [ -d os_desc ]; then
    echo 1       > os_desc/use
    echo 0xcd    > os_desc/b_vendor_code
    echo MSFT100 > os_desc/qw_sign
fi
for fn in ncm.usb0 ncm.usb1; do
    if [ -d "functions/$fn/os_desc/interface.ncm" ]; then
        echo WINNCM > "functions/$fn/os_desc/interface.ncm/compatible_id"
    fi
done

ln -s functions/ncm.usb0 configs/c.1/ 2>/dev/null || true
[ -d functions/ncm.usb1 ] && ln -s functions/ncm.usb1 configs/c.1/ 2>/dev/null
[ -d os_desc ] && ln -s configs/c.1 os_desc/ 2>/dev/null

if ! echo "$UDC" > UDC 2>/dev/null; then
    log "could not bind the gadget to $UDC"
    exit 0
fi

log "NCM gadget bound to $UDC (host $HOST_MAC, device $DEV_MAC)"
if [ -d functions/ncm.usb1 ]; then
    log "Internet card: $(cat functions/ncm.usb1/ifname 2>/dev/null || echo usb1)" "(host $NET_HOST_MAC, device $NET_DEV_MAC, $NET_PI_ADDR via $NET_GATEWAY)"
fi

exit 0
